// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqMobQlHy3mh2DAxpyh0ns9rCo0Vrrz00',
    appId: '1:178341348430:web:35a7005976d20fc33daf1f',
    messagingSenderId: '178341348430',
    projectId: 'biomove-c5ee5',
    authDomain: 'biomove-c5ee5.firebaseapp.com',
    storageBucket: 'biomove-c5ee5.firebasestorage.app',
    measurementId: 'G-R0R7KL7J40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVuI4S-MvZhBrenCp4MsyQIufGOzwhHUE',
    appId: '1:178341348430:android:3f77e0a81c9025c03daf1f',
    messagingSenderId: '178341348430',
    projectId: 'biomove-c5ee5',
    storageBucket: 'biomove-c5ee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUEIFRqmtqHfMxr0T4ic9LajkBiCftRUA',
    appId: '1:178341348430:ios:1d74f732cb5418b73daf1f',
    messagingSenderId: '178341348430',
    projectId: 'biomove-c5ee5',
    storageBucket: 'biomove-c5ee5.firebasestorage.app',
    androidClientId: '178341348430-j5svl1nokaho0alc0bpulckkfti6dn71.apps.googleusercontent.com',
    iosClientId: '178341348430-sen3mj50jt3vbpi4sbtolosa1i58s5tr.apps.googleusercontent.com',
    iosBundleId: 'com.biomove.biomove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUEIFRqmtqHfMxr0T4ic9LajkBiCftRUA',
    appId: '1:178341348430:ios:1d74f732cb5418b73daf1f',
    messagingSenderId: '178341348430',
    projectId: 'biomove-c5ee5',
    storageBucket: 'biomove-c5ee5.firebasestorage.app',
    androidClientId: '178341348430-j5svl1nokaho0alc0bpulckkfti6dn71.apps.googleusercontent.com',
    iosClientId: '178341348430-sen3mj50jt3vbpi4sbtolosa1i58s5tr.apps.googleusercontent.com',
    iosBundleId: 'com.biomove.biomove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqMobQlHy3mh2DAxpyh0ns9rCo0Vrrz00',
    appId: '1:178341348430:web:c5f92fbb63918a153daf1f',
    messagingSenderId: '178341348430',
    projectId: 'biomove-c5ee5',
    authDomain: 'biomove-c5ee5.firebaseapp.com',
    storageBucket: 'biomove-c5ee5.firebasestorage.app',
    measurementId: 'G-P7Z0B3DKND',
  );

}